config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, presence: true

  has_many :statistics, dependent: :destroy
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Games::IndexQuery.call(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.haml
%table
  %thead
    %th= t('.game_name')
    %th
      - if params[:sort] == 'statistics.current_players'
        = link_to t('.current_players'), games_path(sort: '-statistics.current_players')
      - else
        = link_to t('.current_players'), games_path(sort: 'statistics.current_players')
    %th
      - if params[:sort] == 'statistics.peak_today'
        = link_to t('.peak_today'), games_path(sort: '-statistics.peak_today')
      - else
        = link_to t('.peak_today'), games_path(sort: 'statistics.peak_today')
    %th= t('.current_online_rank')
    %th= t('.peak_online_rank')
  %tbody
    - @games.each do |game|
      %tr
        %td= game.name
        %td= game.statistics.last.current_players
        %td= game.statistics.last.peak_today
        %td= game.current_online_rank
        %td= game.peak_online_rank

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SteamStatsApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield